/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package yahtzee;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.function.Consumer;

/**
 *
 * @author kgaritis
 */
public final class PlayerList extends javax.swing.JPanel {


    /**
     * Creates new form PlayerList
     */
    public PlayerList() {
        initComponents();
        PlayerList pl = this;
    }
    private void onPIdxChange(int old, int new_) {
        playerInfo[old].deactivate();
        playerInfo[new_].activate();
    }
    private void onPNameChange(String[] newVal) {
        removeAll();
        String[] newnames = newVal;
        playerInfo = new Player[newnames.length];
        for (int i = 0; i < newnames.length; i++) {
            Player p = new Player(newnames[i]);
            add(p);
            playerInfo[i] = p;
        }
    }

    public void setPlayerStats(int idx, int score, int up, int down) {
        playerInfo[idx].setStats(score, up, down);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents




    /**
     * Get the value of playerNames
     *
     * @return the value of playerNames
     */
    public String[] getPlayerNames() {
        return playerNames;
    }

    public void setPlayerNames(String[] playerNames) {
        this.playerNames = playerNames;
        onPNameChange(this.playerNames);
    }

    public String getPlayerNames(int index) {
        return this.playerNames[index];
    }

    public void setPlayerNames(int index, String playerNames) {
        this.playerNames[index] = playerNames;
        onPNameChange(this.playerNames);
    }



    private int playingidx = 0;

    private String[] playerNames = {};
    public int getActiveidx() {
        return playingidx;
    }

    public void setActiveidx(int playingidx) {
        onPIdxChange(this.playingidx, playingidx);
        this.playingidx = playingidx;
    }

    private Player[] playerInfo = {};


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
