/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yahtzee;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author user
 */
public class StatusIndicator extends javax.swing.JPanel {
    public static final Color ONLINE = Color.GREEN;
    public static final Color OFFLINE = Color.LIGHT_GRAY;
    public static final Color LOBBY = Color.YELLOW;
    public static final Color ERRORS = Color.RED;
    /**
     * Creates new form StatusIndicator
     */
    public StatusIndicator() {
        initComponents();
    }

    @Override
    public void paint(Graphics g1) {
        Graphics2D g = (Graphics2D) g1;
        int hw = getWidth()/2;
        double step = 1/(double)(hw*hw);
        for (int i = hw; i > 1; i--) {
            Color c = getColor(1 - step*i*i);
            g.setColor(c);
            g.fillOval(hw-i, hw-i, i*2, i*2);
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(14, 14));
        setMinimumSize(new java.awt.Dimension(14, 14));
        setPreferredSize(new java.awt.Dimension(14, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private Color getColor(double coeff) {
        return new Color((int)(color.getRed()*coeff), 
                         (int)(color.getGreen()*coeff), 
                         (int)(color.getBlue()*coeff));
    }
    
    public Color getColor() {
        return color;
    }
    
    public void setColor(Color c) {
        this.color = c;
        repaint();
    }
    
    private Color color = OFFLINE;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
